CREATE TABLE NOTICE (
    NOTICE_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    NOTICE_TITLE VARCHAR2(45) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    NOTICE_DATE DATE DEFAULT SYSDATE,
    NOTICE_FILES NVARCHAR2(1000) NULL,
    NOTICE_PUB NUMBER NOT NULL
);
CREATE TABLE FAQ (
    FAQ_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    FAQ_TITLE VARCHAR2(45) NOT NULL,
    FAQ_CONTENT VARCHAR2(4000)  NOT NULL,
    QNA_PUB NUMBER NOT NULL
);
CREATE TABLE QNA (
    QNA_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    QNA_TITLE VARCHAR2(45) NOT NULL,
    QNA_CONTENT VARCHAR2(4000) NOT NULL,
    QNA_DATE DATE DEFAULT SYSDATE,
    QNA_FILES NVARCHAR2(1000) NULL,
    QNA_ANSWER NUMBER DEFAULT 0,
    ANSWER_CONTENT VARCHAR2(4000) NULL,
    ANSWER_FILES NVARCHAR2(1000) NULL
);

CREATE TABLE UPLOAD_FILE
(
    FILE_NO NUMBER PRIMARY KEY,                         --파일 번호
    NOTICE_NO NUMBER NOT NULL,                          --게시판 번호
    QNA_NO NUMBER NOT NULL,                             --게시판 번호
    ORG_FILE_NAME VARCHAR2(260) NOT NULL,               --원본 파일 이름
    STORED_FILE_NAME VARCHAR2(36) NOT NULL,             --변경된 파일 이름
    FILE_SIZE NUMBER,                                   --파일 크기
    REGDATE DATE DEFAULT SYSDATE NOT NULL,              --파일등록일
    DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL,            --삭제구분
);

/* UPLOAD_FILE 시퀀스 생성 */
CREATE SEQUENCE UPLOAD_FILE_SEQ
    START WITH 1 
    INCREMENT BY 1 
    NOMAXVALUE NOCACHE NOCYCLE;

/* NOTICE_SEQ 시퀀스 생성 */
CREATE SEQUENCE NOTICE_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
/* QNA_SEQ 시퀀스 생성 */
CREATE SEQUENCE QNA_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
/* FAQ_SEQ 시퀀스 생성 */
CREATE SEQUENCE FAQ_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/*NOTICE 외래키 제약조건*/
ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE" FOREIGN KEY ("MEMBER_EMAIL")REFERENCES "MEMBER" ("MEMBER_EMAIL") ON DELETE CASCADE ;
/*FAQ 외래키 제약조건*/
ALTER TABLE "FAQ" ADD CONSTRAINT "FK_MEMBER_TO_FAQ" FOREIGN KEY ("MEMBER_EMAIL")REFERENCES "MEMBER" ("MEMBER_EMAIL") ON DELETE CASCADE ;
/*QNA 외래키 제약조건*/
ALTER TABLE "QNA" ADD CONSTRAINT "FK_MEMBER_TO_QNA" FOREIGN KEY ("MEMBER_EMAIL")REFERENCES "MEMBER" ("MEMBER_EMAIL") ON DELETE CASCADE ;
/*UPLOAD_FILE 외래키 제약조건*/
ALTER TABLE "UPLOAD_FILE" ADD CONSTRAINT "FK_"